DROP DATABASE IF EXISTS database_links;
CREATE DATABASE batabase_links CHARSET utf8mb4;
USE database_links;

-- user

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(60) NOT NULL,
    email VARCHAR(120) NOT NULL,
    fullname VARCHAR(100) NOT NULL
);

-- links

CREATE TABLE links (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    description TEXT,
    user_id INT UNSIGNED,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id)
);
